import { addIcons } from 'ionicons';
import {
  homeOutline, home,
  compassOutline, compass,
  leafOutline, leaf,
  calendarOutline, calendar,
  personOutline, personCircleOutline, person,
  searchOutline,
  notificationsOutline, notifications,
  chevronForwardOutline, chevronBackOutline, arrowBackOutline,
  heartOutline, heart,
  chatbubbleOutline, chatbubbleEllipsesOutline,
  shareSocialOutline,
  pencilOutline, pencil,
  cameraOutline,
  addOutline, addCircleOutline,
  star, starOutline, starHalfOutline,
  locationOutline, locationSharp,
  timeOutline, trendingUpOutline,
  bagCheckOutline, constructOutline, partlySunnyOutline,
  checkmarkCircle, checkmarkOutline, closeOutline, close,
  logOutOutline, shieldCheckmarkOutline, helpCircleOutline,
  informationCircleOutline, sendOutline, trashOutline,
  flagOutline, mailOutline, callOutline,
  maleFemaleOutline, peopleOutline, imageOutline, ellipsisHorizontal,
  ribbonOutline, walkOutline, thermometerOutline,
} from 'ionicons/icons';

export function registerAppIcons() {
  addIcons({
    'home-outline': homeOutline,
    'home': home,
    'compass-outline': compassOutline,
    'compass': compass,
    'leaf-outline': leafOutline,
    'leaf': leaf,
    'calendar-outline': calendarOutline,
    'calendar': calendar,
    'person-outline': personOutline,
    'person-circle-outline': personCircleOutline,
    'person': person,
    'search-outline': searchOutline,
    'notifications-outline': notificationsOutline,
    'notifications': notifications,
    'chevron-forward-outline': chevronForwardOutline,
    'chevron-back-outline': chevronBackOutline,
    'arrow-back-outline': arrowBackOutline,
    'heart-outline': heartOutline,
    'heart': heart,
    'chatbubble-outline': chatbubbleOutline,
    'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
    'share-social-outline': shareSocialOutline,
    'pencil-outline': pencilOutline,
    'pencil': pencil,
    'camera-outline': cameraOutline,
    'add-outline': addOutline,
    'add-circle-outline': addCircleOutline,
    'star': star,
    'star-outline': starOutline,
    'star-half-outline': starHalfOutline,
    'location-outline': locationOutline,
    'location-sharp': locationSharp,
    'time-outline': timeOutline,
    'trending-up-outline': trendingUpOutline,
    'bag-check-outline': bagCheckOutline,
    'construct-outline': constructOutline,
    'partly-sunny-outline': partlySunnyOutline,
    'checkmark-circle': checkmarkCircle,
    'checkmark-outline': checkmarkOutline,
    'close-outline': closeOutline,
    'close': close,
    'log-out-outline': logOutOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'help-circle-outline': helpCircleOutline,
    'information-circle-outline': informationCircleOutline,
    'send-outline': sendOutline,
    'trash-outline': trashOutline,
    'flag-outline': flagOutline,
    'mail-outline': mailOutline,
    'call-outline': callOutline,
    'male-female-outline': maleFemaleOutline,
    'people-outline': peopleOutline,
    'image-outline': imageOutline,
    'ellipsis-horizontal': ellipsisHorizontal,
    'ribbon-outline': ribbonOutline,
    'walk-outline': walkOutline,
    'thermometer-outline': thermometerOutline,
  });
}
