// GENERATED by tools/fetch-trail-photos.mjs — but REVIEW BEFORE TRUSTING.
// Every photo below must actually be a picture of that mountain. Commons
// search can return the view FROM a peak, a map, or a different summit.
//
// The credit and license fields are a licence condition, not decoration. The
// trail sheet renders them over the photo — leave that in place.

export interface TrailPhoto {
  url: string;
  credit?: string;
  license?: string;
  source?: string;
}

export const TRAIL_PHOTOS: Record<string, TrailPhoto> = {
  T002: {
    url: "assets/trails/T002.jpg",
    credit: "Biag arnel",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mt._Batulao,_Nasugbu,_Batangas,_Philippines.jpg",
  },
  T003: {
    url: "assets/trails/T003.jpg",
    credit: "Jpcabarles",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mt._Ulap_2.jpg",
  },
  T004: {
    url: "assets/trails/T004.jpg",
    credit: "Lance Vanlewen",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Crater_Lake_at_the_Mount_Pinatubo_Caldera_in_the_Philippines_(2).jpg",
  },
  T006: {
    url: "assets/trails/T006.jpg",
    credit: "Patrickroque01",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pico_De_Loro_view_from_Manila_Bay_(Maragondon,_Cavite;_01-08-2024).jpg",
  },
  T007: {
    url: "assets/trails/T007.jpg",
    credit: "Judgefloro",
    license: "CC0",
    source: "https://commons.wikimedia.org/wiki/File:9993Kaledian_Camba_Arayat,_Pampanga_21.jpg",
  },
  T010: {
    url: "assets/trails/T010.jpg",
    credit: "Ramon FVelasquez",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cuenca,Batangasjf1789_01.JPG",
  },
  T013: {
    url: "assets/trails/T013.jpg",
    credit: "Arius1998",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mounts_Pamitinan_and_Binacayan.jpg",
  },
  T014: {
    url: "assets/trails/T014.jpg",
    credit: "Arius1998",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mount_Pamitinan_facing_Mount_Binacayan.jpg",
  },
  T019: {
    url: "assets/trails/T019.jpg",
    credit: "Judgefloro",
    license: "CC0",
    source: "https://commons.wikimedia.org/wiki/File:9282Bagumbong,_Jalajala,_Rizal_24.jpg",
  },
  T021: {
    url: "assets/trails/T021.jpg",
    credit: "JHSolis",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mount_Makiling.jpg",
  },
  T022: {
    url: "assets/trails/T022.jpg",
    credit: "Jewelson Solis",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mt._Makiling_01.jpg",
  },
  T023: {
    url: "assets/trails/T023.jpg",
    credit: "Floro granada",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mount_Banahaw_and_Mount_San_Cristobal.jpg",
  },
  T025: {
    url: "assets/trails/T025.jpg",
    credit: "Ervin Malicdem",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mt._Marami_and_Mataas_na_Gulod.jpg",
  },
  T030: {
    url: "assets/trails/T030.jpg",
    credit: "Patrickroque01",
    license: "CC BY-SA 4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mount_Ugo_view_from_Mines_View_Baguio_(Itogon,_Benguet;_12-04-2022).jpg",
  },
};

const PLACEHOLDER =
  'data:image/svg+xml;utf8,' +
  encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="160" viewBox="0 0 400 160">
      <defs>
        <linearGradient id="s" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="#1b2a20"/>
          <stop offset="100%" stop-color="#0d1711"/>
        </linearGradient>
      </defs>
      <rect width="400" height="160" fill="url(#s)"/>
      <path d="M0 160 L95 70 L150 112 L225 44 L300 110 L350 82 L400 128 L400 160 Z" fill="#25382b"/>
      <path d="M0 160 L70 108 L135 140 L210 96 L280 138 L340 116 L400 152 L400 160 Z" fill="#3a5442"/>
    </svg>`.replace(/\s+/g, ' '),
  );

export function photoFor(id: string): TrailPhoto {
  return TRAIL_PHOTOS[id] ?? { url: PLACEHOLDER };
}

export function hasPhoto(id: string): boolean {
  return !!TRAIL_PHOTOS[id];
}
